---

- block:
    - name: Ensure PostgreSQL is running
      service:
        name: postgresql
        state: started
        enabled: yes

    - name: Create PostgreSQL databases
      become_user: postgres
      postgresql_db:
        state: "{{ item.state | default('present') }}"
        name: "{{ item.name }}"
        owner: "{{ item.owner }}"
      with_items:
        - "{{ postgresql_databases }}"
  when: postgresql_databases|length > 0