---

- block:
    - name: Ensure PostgreSQL is running
      service:
        name: postgresql
        state: started
        enabled: yes

    - name: Install postgis apt packages
      apt:
        pkg: "postgresql-{{ postgresql_version }}-postgis-*"
        state: "{{ item.state }}"
        update_cache: yes
        cache_valid_time: 3600
      when: 'item.name == "postgis"'
      with_items:
        - "{{ postgresql_extensions }}"

    - name: Add PostgreSQL extensions
      become_user: postgres
      postgresql_ext:
        state: "{{ item[1].state | default('present') }}"
        db: "{{ item[0].name }}"
        name: "{{ item[1].name }}"
      with_nested:
        - "{{ postgresql_databases }}"
        - "{{ postgresql_extensions }}"
  when: (postgresql_databases|length > 0) and (postgresql_extensions|length > 0)