---

- include: setup.yml
  tags: [postgresql, postgresql-installation]

- include: configuration.yml
  tags: [postgresql, postgresql-configuration]

- block:
    - include: psycopg2.yml
      tags: [postgresql, postgresql-users, postgresql-databases, postgresql-extensions]

    - include: users.yml
      tags: [postgresql, postgresql-users]

    - include: databases.yml
      tags: [postgresql, postgresql-databases] 

    - include: extensions.yml
      tags: [postgresql, postgresql-extensions]
  when: not postgresql_standby_mode

- include: replication.yml
  when: postgresql_standby_mode
  tags: [postgresql, postgresql-replication]
