---
sudo: required

services: docker

env:
  - DISTRIBUTION: ubuntu
    DISTRIBUTION_VERSION: 16.04
    ANSIBLE_VERSION: 2.4.0.0
    DOCKER_INIT: /lib/systemd/systemd

before_install:
  - |
    set -e

    docker run -d -v "${PWD}/tests":/tmp/tests --name="${DISTRIBUTION}-${DISTRIBUTION_VERSION}" --privileged ${DISTRIBUTION}:${DISTRIBUTION_VERSION} ${DOCKER_INIT}
    sleep 3
    docker exec ${DISTRIBUTION}-${DISTRIBUTION_VERSION} true
    docker exec -t ${DISTRIBUTION}-${DISTRIBUTION_VERSION} /bin/sh -c "apt -qq update"
    docker exec -t ${DISTRIBUTION}-${DISTRIBUTION_VERSION} /bin/sh -c "locale-gen"
install:
  - docker exec -t ${DISTRIBUTION}-${DISTRIBUTION_VERSION} /bin/sh -c "apt -qq install sudo python-pip git curl -y > /dev/null && pip install --upgrade pip -q && pip install ansible==${ANSIBLE_VERSION} -q"
  - docker exec -t ${DISTRIBUTION}-${DISTRIBUTION_VERSION} /bin/sh -c "ansible --version"

script:
  - docker exec -t ${DISTRIBUTION}-${DISTRIBUTION_VERSION} /bin/sh -c "ansible-galaxy install -r /tmp/tests/requirements.yml"
  - docker exec -t ${DISTRIBUTION}-${DISTRIBUTION_VERSION} /bin/sh -c "git clone https://github.com/kostiantyn-nemchenko/ansible-module-postgresql-setting /tmp/postgresql-setting"
  - docker exec -t ${DISTRIBUTION}-${DISTRIBUTION_VERSION} /bin/sh -c "ANSIBLE_LIBRARY=/tmp/postgresql-setting/library ansible-playbook -i /tmp/tests/inventory /tmp/tests/test.yml --syntax-check"
  - docker exec -t ${DISTRIBUTION}-${DISTRIBUTION_VERSION} /bin/sh -c "ANSIBLE_LIBRARY=/tmp/postgresql-setting/library ansible-playbook -i /tmp/tests/inventory /tmp/tests/test.yml -Dvv"

#notifications:
#  webhooks: https://galaxy.ansible.com/api/v1/notifications/  