---
- import_tasks: sysctl.yml
  when: postgresql_sysctl_conf |length > 0

- name: Configure PostgreSQL pgpass-based access
  template:
    src: pgpass.j2
    dest: "{{ postgresql_home_dir }}/.pgpass"
    owner: postgres
    group: postgres
    mode: 0600
  when: postgresql_pgpass_conf |length > 0

- name: Configure PostgreSQL host-based authentication
  template:
    src: pg_hba.conf.j2
    dest: "{{ postgresql_config_dir }}/pg_hba.conf"
    owner: postgres
    group: postgres
    mode: 0644
  when: postgresql_hba_conf |length > 0
  notify:
    - Reload PostgreSQL

- name: Configure server settings
  block:
    - replace:
        path: "{{ postgresql_config_dir }}/postgresql.conf"
        replace: "{{ (item.guc + ' = ' + item.value) if item.state == 'present' else ('#' + item.guc + ' = ' + item.value) }}"
        regexp: "^#?{{ item.guc }} =(\\s*)(('.*')|(\\S*))(?=(?#))"
        owner: postgres
        group: postgres
        mode: 0644
      when: item.context != "postmaster"
      with_items:
        - "{{ postgresql_conf }}"
      notify:
        - Reload PostgreSQL

    - replace:
        path: "{{ postgresql_config_dir }}/postgresql.conf"
        replace: "{{ (item.guc + ' = ' + item.value) if item.state == 'present' else ('#' + item.guc + ' = ' + item.value) }}"
        regexp: "^#?{{ item.guc }} =(\\s*)(('.*')|(\\S*))(?=(?#))"
        owner: postgres
        group: postgres
        mode: 0644
      when: item.context == "postmaster"
      with_items:
        - "{{ postgresql_conf }}"
      notify:
        - Restart PostgreSQL
  when: postgresql_conf |length > 0

- meta: flush_handlers
