---
- name: Configure PostgreSQL pgpass-based access
  become_user: postgres
  template:
    src: pgpass.j2
    dest: "{{ postgresql_home_dir }}/.pgpass"
    owner: postgres
    group: postgres
    mode: 0600
  when: postgresql_pgpass_rules |length > 0

- name: Configure PostgreSQL host-based authentication
  template: 
    src: pg_hba.conf.j2 
    dest: "{{ postgresql_config_dir }}/pg_hba.conf"
    owner: postgres
    group: postgres
    mode: 0644
  when: postgresql_hba_access |length > 0
  notify:
    - Reload PostgreSQL

- block:
    - name: Configure PostgreSQL settings - postgres reload is enough to apply config changes
      become_user: postgres
      postgresql_setting:
        guc: "{{ item.guc }}"
        state: "{{ item.state|default('present') }}"
        value: "{{ item.value|default(None) }}"
        port: "{{ postgresql_port|default(5432) }}"
      when: item.context != "postmaster"
      with_items:
        - "{{ postgresql_config_settings }}"
      notify:
        - Reload PostgreSQL

    - name: Configure PostgreSQL settings - postgres restart is required to apply config changes
      become_user: postgres
      postgresql_setting:
        guc: "{{ item.guc }}"
        state: "{{ item.state|default('present') }}"
        value: "{{ item.value|default(None) }}"
        port: "{{ postgresql_port|default(5432) }}"
      when: item.context == "postmaster"
      with_items:
        - "{{ postgresql_config_settings }}"
      notify:
        - Restart PostgreSQL
  when: postgresql_config_settings |length > 0
