---
- name: Include OS-specific variables
  include_vars: "{{ ansible_distribution }}-{{ ansible_distribution_version.split('.')[0] }}.yml"
  tags: ['postgresql-installation']

- import_tasks: installation.yml
  tags: ['postgresql-installation']

- name: Ensure PostgreSQL is running
  service:
    name: postgresql
    state: started
    enabled: yes
  tags:
    - postgresql-users
    - postgresql-databases
    - postgresql-extensions

- import_tasks: psycopg2.yml
  tags:
    - postgresql-users
    - postgresql-databases
    - postgresql-extensions

- meta: flush_handlers

- import_tasks: configuration.yml
  tags: ['postgresql-configuration']

- import_tasks: users.yml
  tags: ['postgresql-users']

- import_tasks: databases.yml
  tags: ['postgresql-databases']

- import_tasks: extensions.yml
  tags: ['postgresql-extensions']
