---

  - name: Start PostgreSQL
    service: 
      name: postgresql
      state: started

  - name: Restart PostgreSQL
    service: 
      name: postgresql
      state: restarted

  - name: Reload PostgreSQL
    service: 
      name: postgresql
      state: reloaded
